# This is a basic workflow to help you get started with Actions

name: CVE and Docs update

# Controls when the workflow will run
on:
  # Scheudle every sunday at 00:00
  #schedule:
  #  - cron: '0 0 * * 0'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup MySQL Tuner repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pwd
          cd build
          pwd
          sudo bash ./installStaff.sh

      - name: Update CVE and docs
        run: |
          pwd
          cd ./build
          pwd
          sudo bash ./updateStaff.sh

      - name: Run the Action
        uses: devops-infra/action-commit-push@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          add_timestamp: true
          commit_prefix: "[AUTO]"
          commit_message: "Updates CVE and docs (via Actions)"
          force: false
          target_branch: "cve-docs"